# Generated by Django 3.2.6 on 2021-08-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foursomeregistration',
            name='is_payed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
