# Generated by Django 3.2.6 on 2021-10-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_foursomeregistration_is_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='foursomeregistration',
            name='four',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
