# Generated by Django 3.2.6 on 2021-08-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoursomeRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_code', models.CharField(max_length=12)),
                ('payment_id', models.CharField(max_length=100)),
                ('contact_email', models.CharField(max_length=100)),
                ('golf_1_fname', models.CharField(max_length=50)),
                ('golf_1_lname', models.CharField(max_length=50)),
                ('golf_2_fname', models.CharField(max_length=50)),
                ('golf_2_lname', models.CharField(max_length=50)),
                ('golf_3_fname', models.CharField(max_length=50)),
                ('golf_3_lname', models.CharField(max_length=50)),
                ('golf_4_fname', models.CharField(max_length=50)),
                ('golf_4_lname', models.CharField(max_length=50)),
            ],
        ),
    ]
