# Generated by Django 3.2.6 on 2021-08-14 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custAdmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoursomeRegistration',
        ),
    ]
